### ISSUE TITLE
Iguala comp getting all Arttypes instead of just Iguala Arttypes

### ISSUE THREAD

**Issue by EduardoVaca** [JuanGro/Balarco#22]
This is just a basic template better suited for bug reporting, if it is not suitable for the thing you want to report such as a problem with the documentation, feel free to deviate from it.

Iguala comp getting all Arttypes instead of just Iguala Arttypes

## Context

Iguala should only be able to add art types related to iguala

## Expected result

On Iguala Form the art type list should only contain iguala art types

## Current result

Get all art types even graduation ones

This template was adapted ~stolen~ from [Aurelia Moser](https://bl.ocks.org/auremoser/72803ba969d0e61ff070)

**Comment by JuanGro** [comment]
Can I close this?
