### ISSUE TITLE
User Update without roles selected

### ISSUE THREAD

**Issue by EduardoVaca** [JuanGro/Balarco#49]
This is just a basic template better suited for bug reporting, if it is not suitable for the thing you want to report such as a problem with the documentation, feel free to deviate from it.

## Context

When the user is selected to be modified the roles he has are not selected in the picker. This cause an Internal Server Error

## Expected result

When user selected the roles should be chosen in the picker by default

## Current result

When user selected there are no roles selected

This template was adapted ~stolen~ from [Aurelia Moser](https://bl.ocks.org/auremoser/72803ba969d0e61ff070)

**Comment by JuanGro** [comment]
When I changed the multipicker for ng2-select, that error was fixed.
